### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by mroads-engg** [samj1912/ltr-demo#11]
When I am trying to search using the http://localhost:5000, it throws up error stating 

"_**The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application**_".

I am using Mac Mojave 10.14.4 and running Google chrome for accessing 8983 and 5000 ports. Solr (version 7.6.0) is indexed and running fine on 8983 port. 

The other strange thing I found at http://localhost:5000 is that, when I enter a query such as 'a' or 'as' which is not indexed in solr, it doesn't thows up an error but at the same time displays no results/comments.

**Comment by sambhav** [comment]
Hey, I am not able to replicate the ISE. Can you exactly describe the steps to reproduce the bug? Also are you sure that no other service is running on that port?

**Comment by sambhav** [comment]
Closing this for now. Feel free to reopen if you can reproduce it.
